services:
  - type: web
    name: vidyai
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      cd VidyAI
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: cd VidyAI && gunicorn vidyai.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: GEMINI_API_KEY
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: vidyai.settings
      - key: DATABASE_URL
        fromDatabase:
          name: vidyai_db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "*"
