# Generated by Django 4.2.10 on 2025-04-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_lesson_estimated_duration_quiz_created_at_quiz_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='passing_score',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=30),
        ),
    ]
