# Generated by Django 4.2.10 on 2025-04-11 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(choices=[('video', 'Video'), ('reading', 'Reading'), ('exercise', 'Exercise'), ('project', 'Project'), ('experiment', 'Experiment')], max_length=20)),
                ('content', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=15)),
                ('points_reward', models.PositiveIntegerField(default=5)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='LearningGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('game_type', models.CharField(choices=[('quiz', 'Quiz Game'), ('puzzle', 'Puzzle'), ('memory', 'Memory Game'), ('matching', 'Matching Game'), ('interactive', 'Interactive Story')], max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='games/')),
                ('min_age', models.PositiveIntegerField(default=5)),
                ('max_age', models.PositiveIntegerField(default=18)),
                ('points_reward', models.PositiveIntegerField(default=10)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='LearningStyleAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_score', models.PositiveIntegerField(default=0)),
                ('auditory_score', models.PositiveIntegerField(default=0)),
                ('kinesthetic_score', models.PositiveIntegerField(default=0)),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_assessments', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmotionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('engaged', 'Engaged'), ('confused', 'Confused'), ('bored', 'Bored'), ('frustrated', 'Frustrated'), ('happy', 'Happy'), ('tired', 'Tired')], max_length=20)),
                ('confidence', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_data', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserGameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('highest_level', models.PositiveIntegerField(default=1)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('time_played_seconds', models.PositiveIntegerField(default=0)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learninggame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_progress', to='core.userprofile')),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='UserActivityCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learningactivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_activities', to='core.userprofile')),
            ],
            options={
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
